spring.application.name=ingresso-api
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:ingressodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.h2.console.path=/h2-console
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
token.secret=change-this-secret-in-production

server.port=8081