ALTER TABLE issued_tickets ADD COLUMN refunded_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE ticket_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    source VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    amount_in_cents BIGINT NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_ticket_refunds_ticket UNIQUE (ticket_id),
    CONSTRAINT fk_ticket_refunds_ticket FOREIGN KEY (ticket_id) REFERENCES issued_tickets(id),
    CONSTRAINT fk_ticket_refunds_order FOREIGN KEY (order_id) REFERENCES ticket_orders(id),
    CONSTRAINT fk_ticket_refunds_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_ticket_refunds_actor FOREIGN KEY (actor_user_id) REFERENCES usuarios(id),
    CONSTRAINT ck_ticket_refunds_amount CHECK (amount_in_cents >= 0)
);

CREATE INDEX idx_ticket_refunds_event_created ON ticket_refunds (event_id, created_at);