CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    usuario_perfil VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario_perfis (
    usuario_id BIGINT NOT NULL,
    perfil VARCHAR(50) NOT NULL,
    CONSTRAINT pk_usuario_perfis PRIMARY KEY (usuario_id, perfil),
    CONSTRAINT fk_usuario_perfis_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE legacy_admin_demotions (
    usuario_id BIGINT PRIMARY KEY,
    email VARCHAR(255) NOT NULL
);

INSERT INTO legacy_admin_demotions (usuario_id, email)
SELECT id, email
FROM usuarios
WHERE usuario_perfil = 'ADMIN';

INSERT INTO usuario_perfis (usuario_id, perfil)
SELECT usuario.id, CASE WHEN usuario.usuario_perfil = 'ADMIN' THEN 'USER' ELSE usuario.usuario_perfil END
FROM usuarios usuario
WHERE NOT EXISTS (
    SELECT 1
    FROM usuario_perfis perfil
    WHERE perfil.usuario_id = usuario.id
      AND perfil.perfil = CASE WHEN usuario.usuario_perfil = 'ADMIN' THEN 'USER' ELSE usuario.usuario_perfil END
);

ALTER TABLE usuarios DROP COLUMN usuario_perfil;