CREATE TABLE producer_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    accepted_by_user_id BIGINT,
    accepted_at TIMESTAMP WITH TIME ZONE,
    revoked_by_user_id BIGINT,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_producer_invitation_creator FOREIGN KEY (created_by_user_id) REFERENCES usuarios(id),
    CONSTRAINT fk_producer_invitation_acceptor FOREIGN KEY (accepted_by_user_id) REFERENCES usuarios(id),
    CONSTRAINT fk_producer_invitation_revoker FOREIGN KEY (revoked_by_user_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_producer_invitation_email_status
    ON producer_invitations (email, status, expires_at);

CREATE TABLE permission_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    actor_email VARCHAR(255) NOT NULL,
    target_user_id BIGINT,
    target_email VARCHAR(255) NOT NULL,
    permission VARCHAR(50) NOT NULL,
    action VARCHAR(40) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_permission_audit_actor FOREIGN KEY (actor_user_id) REFERENCES usuarios(id),
    CONSTRAINT fk_permission_audit_target FOREIGN KEY (target_user_id) REFERENCES usuarios(id)
);

INSERT INTO permission_audits (
    actor_user_id,
    actor_email,
    target_user_id,
    target_email,
    permission,
    action,
    occurred_at
)
SELECT
    NULL,
    'legacy-database-migration',
    usuario_id,
    email,
    'ADMIN',
    'LEGACY_ADMIN_DEMOTED',
    CURRENT_TIMESTAMP
FROM legacy_admin_demotions;

DROP TABLE legacy_admin_demotions;