CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    description VARCHAR(5000) NOT NULL,
    image_url VARCHAR(2048) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    venue_name VARCHAR(200) NOT NULL,
    street_address VARCHAR(300) NOT NULL,
    city VARCHAR(120) NOT NULL,
    state_code VARCHAR(2) NOT NULL,
    age_classification VARCHAR(80) NOT NULL,
    organizer VARCHAR(200) NOT NULL,
    status VARCHAR(20) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_events_producer FOREIGN KEY (producer_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_events_status_starts_at ON events (status, starts_at);
CREATE INDEX idx_events_producer ON events (producer_id);

CREATE TABLE ticket_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    price_in_cents BIGINT NOT NULL,
    admission_mode VARCHAR(30) NOT NULL,
    configured_quantity INTEGER,
    sold_quantity INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_ticket_category_code UNIQUE (event_id, code),
    CONSTRAINT fk_ticket_categories_event FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE seat_sectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    position_index INTEGER NOT NULL,
    CONSTRAINT uq_seat_sector_name UNIQUE (event_id, name),
    CONSTRAINT fk_seat_sectors_event FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE seat_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id BIGINT NOT NULL,
    label VARCHAR(20) NOT NULL,
    position_index INTEGER NOT NULL,
    CONSTRAINT uq_seat_row_label UNIQUE (sector_id, label),
    CONSTRAINT fk_seat_rows_sector FOREIGN KEY (sector_id) REFERENCES seat_sectors(id)
);

CREATE TABLE event_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    label VARCHAR(20) NOT NULL,
    position_index INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT uq_event_seat_label UNIQUE (row_id, label),
    CONSTRAINT fk_event_seats_row FOREIGN KEY (row_id) REFERENCES seat_rows(id),
    CONSTRAINT fk_event_seats_category FOREIGN KEY (ticket_category_id) REFERENCES ticket_categories(id)
);