ALTER TABLE ticket_categories ADD COLUMN reserved_quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE event_seats ADD COLUMN reserved_order_id BIGINT;

CREATE TABLE ticket_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_payload_hash VARCHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_in_cents BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reservation_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    paid_at TIMESTAMP WITH TIME ZONE,
    provider_reference VARCHAR(128),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_ticket_orders_buyer_idempotency UNIQUE (buyer_id, idempotency_key),
    CONSTRAINT fk_ticket_orders_buyer FOREIGN KEY (buyer_id) REFERENCES usuarios(id),
    CONSTRAINT fk_ticket_orders_event FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE INDEX idx_ticket_orders_status_expiry ON ticket_orders (status, reservation_expires_at);
CREATE INDEX idx_ticket_orders_buyer_created ON ticket_orders (buyer_id, created_at);
CREATE INDEX idx_ticket_orders_event_status ON ticket_orders (event_id, status);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    category_code_snapshot VARCHAR(40) NOT NULL,
    category_name_snapshot VARCHAR(120) NOT NULL,
    admission_mode_snapshot VARCHAR(30) NOT NULL,
    unit_price_in_cents BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES ticket_orders(id),
    CONSTRAINT fk_order_items_category FOREIGN KEY (ticket_category_id) REFERENCES ticket_categories(id)
);

CREATE TABLE order_item_seats (
    order_item_id BIGINT NOT NULL,
    event_seat_id BIGINT NOT NULL,
    sector_name VARCHAR(100) NOT NULL,
    row_label VARCHAR(20) NOT NULL,
    seat_label VARCHAR(20) NOT NULL,
    CONSTRAINT pk_order_item_seats PRIMARY KEY (order_item_id, event_seat_id),
    CONSTRAINT fk_order_item_seats_item FOREIGN KEY (order_item_id) REFERENCES order_items(id)
);

ALTER TABLE event_seats
    ADD CONSTRAINT fk_event_seats_reserved_order FOREIGN KEY (reserved_order_id) REFERENCES ticket_orders(id);

CREATE TABLE payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    attempt_key VARCHAR(64) NOT NULL UNIQUE,
    outcome VARCHAR(20) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_payment_attempts_order FOREIGN KEY (order_id) REFERENCES ticket_orders(id)
);

CREATE INDEX idx_payment_attempts_order ON payment_attempts (order_id, started_at);