CREATE TABLE issued_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    unit_number INTEGER NOT NULL,
    seat_event_id BIGINT,
    sector_snapshot VARCHAR(100),
    row_snapshot VARCHAR(20),
    seat_label_snapshot VARCHAR(20),
    qr_token VARCHAR(64) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_issued_tickets_qr UNIQUE (qr_token),
    CONSTRAINT uq_issued_tickets_item_unit UNIQUE (order_item_id, unit_number),
    CONSTRAINT uq_issued_tickets_seat UNIQUE (seat_event_id),
    CONSTRAINT fk_issued_tickets_order FOREIGN KEY (order_id) REFERENCES ticket_orders(id),
    CONSTRAINT fk_issued_tickets_item FOREIGN KEY (order_item_id) REFERENCES order_items(id),
    CONSTRAINT fk_issued_tickets_seat FOREIGN KEY (seat_event_id) REFERENCES event_seats(id),
    CONSTRAINT ck_issued_tickets_unit CHECK (unit_number > 0)
);

CREATE INDEX idx_issued_tickets_order ON issued_tickets (order_id, id);