CREATE TABLE entry_check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    issued_ticket_id BIGINT,
    operator_user_id BIGINT NOT NULL,
    client_scan_id VARCHAR(36) NOT NULL,
    qr_token_hash VARCHAR(64),
    source VARCHAR(20) NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    device_scanned_at TIMESTAMP WITH TIME ZONE,
    synchronized_at TIMESTAMP WITH TIME ZONE,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_entry_check_ins_operator_scan UNIQUE (operator_user_id, client_scan_id),
    CONSTRAINT fk_entry_check_ins_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_entry_check_ins_ticket FOREIGN KEY (issued_ticket_id) REFERENCES issued_tickets(id),
    CONSTRAINT fk_entry_check_ins_operator FOREIGN KEY (operator_user_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_entry_check_ins_event_time ON entry_check_ins (event_id, processed_at);
CREATE INDEX idx_entry_check_ins_ticket_time ON entry_check_ins (issued_ticket_id, processed_at);

CREATE TABLE entry_check_in_corrections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in_id BIGINT NOT NULL,
    ticket_id BIGINT NOT NULL,
    admin_user_id BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    corrected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_entry_correction_ticket UNIQUE (ticket_id),
    CONSTRAINT fk_entry_correction_check_in FOREIGN KEY (check_in_id) REFERENCES entry_check_ins(id),
    CONSTRAINT fk_entry_correction_ticket FOREIGN KEY (ticket_id) REFERENCES issued_tickets(id),
    CONSTRAINT fk_entry_correction_admin FOREIGN KEY (admin_user_id) REFERENCES usuarios(id)
);