CREATE TABLE event_staff_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    email VARCHAR(320) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    invited_by_user_id BIGINT NOT NULL,
    accepted_by_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_event_staff_invitation_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_event_staff_invitation_inviter FOREIGN KEY (invited_by_user_id) REFERENCES usuarios(id),
    CONSTRAINT fk_event_staff_invitation_acceptor FOREIGN KEY (accepted_by_user_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_event_staff_invitation_email ON event_staff_invitations (event_id, email, expires_at);
CREATE INDEX idx_event_staff_grant_user ON event_staff_invitations (event_id, accepted_by_user_id, revoked_at);

CREATE TABLE offline_entry_manifests (
    id VARCHAR(36) PRIMARY KEY,
    event_id BIGINT NOT NULL,
    operator_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_offline_manifest_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_offline_manifest_operator FOREIGN KEY (operator_user_id) REFERENCES usuarios(id)
);

CREATE TABLE offline_entry_manifest_tickets (
    manifest_id VARCHAR(36) NOT NULL,
    qr_token_hash VARCHAR(64) NOT NULL,
    PRIMARY KEY (manifest_id, qr_token_hash),
    CONSTRAINT fk_offline_manifest_tickets_manifest FOREIGN KEY (manifest_id) REFERENCES offline_entry_manifests(id)
);