package org.example.ingresso.ingresso.migration;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

class LegacyUserMigrationTest {

    @Test
    void preservesUsersButDemotesLegacyAdministrators() throws Exception {
        String databaseUrl = "jdbc:h2:mem:legacy" + UUID.randomUUID().toString().replace("-", "")
            + ";DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(databaseUrl, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE usuarios (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL UNIQUE,
                    email VARCHAR(255) NOT NULL UNIQUE,
                    senha VARCHAR(255) NOT NULL,
                    usuario_perfil VARCHAR(255) NOT NULL
                )
                """);
            statement.execute("INSERT INTO usuarios (nome, email, senha, usuario_perfil) "
                + "VALUES ('Buyer', 'buyer@example.com', 'encoded', 'USER')");
            statement.execute("INSERT INTO usuarios (nome, email, senha, usuario_perfil) "
                + "VALUES ('Legacy admin', 'legacy-admin@example.com', 'encoded', 'ADMIN')");
        }

        Flyway.configure()
            .dataSource(databaseUrl, "sa", "")
            .baselineOnMigrate(true)
            .baselineVersion("0")
            .locations("classpath:db/migration")
            .load()
            .migrate();

        try (Connection connection = DriverManager.getConnection(databaseUrl, "sa", "");
             Statement statement = connection.createStatement()) {
            try (ResultSet users = statement.executeQuery(
                "SELECT COUNT(*) FROM usuarios WHERE email IN ('buyer@example.com', 'legacy-admin@example.com')"
            )) {
                users.next();
                assertEquals(2, users.getInt(1));
            }
            try (ResultSet roles = statement.executeQuery(
                "SELECT perfil FROM usuario_perfis WHERE usuario_id = "
                    + "(SELECT id FROM usuarios WHERE email = 'legacy-admin@example.com')"
            )) {
                roles.next();
                assertEquals("USER", roles.getString(1));
                assertFalse(roles.next());
            }
            try (ResultSet audit = statement.executeQuery(
                "SELECT COUNT(*) FROM permission_audits WHERE target_email = 'legacy-admin@example.com' "
                    + "AND action = 'LEGACY_ADMIN_DEMOTED'"
            )) {
                audit.next();
                assertEquals(1, audit.getInt(1));
            }
        }
    }
}